name: Dubizzle Toyota Scraper Bot

on:
  repository_dispatch:
    types: [cron_trigger]
  workflow_dispatch: # يتيح لك التشغيل اليدوي للتجربة من موقع GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          SCRAPER_API_KEY2: ${{ secrets.SCRAPER_API_KEY2 }}
          SCRAPINGANT_API_KEY: ${{ secrets.SCRAPINGANT_API_KEY }}
          SCRAPINGANT_API_KEY2: ${{ secrets.SCRAPINGANT_API_KEY2 }}
        run: python main.py

      - name: Commit and Push Updated DB
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sent_ads.db
          git commit -m "update sent_ads.db [skip ci]" || exit 0
          git push